/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountSettings: typeof import('./src/components/account/AccountSettings.vue')['default']
    AddFriendDialog: typeof import('./src/components/dialog/AddFriendDialog.vue')['default']
    Chat: typeof import('./src/components/messenger/Chat.vue')['default']
    ChatRoomList: typeof import('./src/components/messenger/ChatRoomList.vue')['default']
    CreateChatRoomDialog: typeof import('./src/components/dialog/CreateChatRoomDialog.vue')['default']
    DirectChat: typeof import('./src/components/messenger/DirectChat.vue')['default']
    FriendRequestDialog: typeof import('./src/components/dialog/FriendRequestDialog.vue')['default']
    Friends: typeof import('./src/components/messenger/Friends.vue')['default']
    InvitationLinkDialog: typeof import('./src/components/dialog/InvitationLinkDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
