/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/Chat.vue')['default']
    ChatRoomList: typeof import('./src/components/ChatRoomList.vue')['default']
    ComponentFinder: typeof import('./src/components/ComponentFinder.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InvitationLinkDialog: typeof import('./src/components/dialog/InvitationLinkDialog.vue')['default']
    Login: typeof import('./src/pages/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/pages/SignUp.vue')['default']
  }
}
